insert into department (name) values 
("marketing"),
("HR"),
("Technical"),
("Sales");

insert into role (title, salary, department_id) values
("software developer", 70000, 3),
("general manager",100000, 2),
("FOH", 60000, 4),
("market analysis", 70000, 1),
("project manager", 100000, 3),
("innovator", 80000, 1),
("specialist", 80000, 1),
("talent manager", 80000, 2),
("training and development", 80000, 2),
("System security specialist", 120000, 3),
("sale manager", 100000, 4),
("accounting", 70000, 4);

insert into employee (first_name, last_name, role_id) values
('Bernelle', 'MacCosty', 10),
('Frederik', 'Gilluley', 12),
('Corny', 'Enos', 11),
('Clovis', 'Devall', 10),
('Sayres', 'Helleker', 7),
('Debee', 'Goddard', 12),
('Ferdinand', 'O''Flaherty', 1),
('Nert', 'Phelp', 12),
('Barbaraanne', 'Tellwright', 6),
('Waly', 'Perott', 3),
('Kath', 'Theodore', 1),
('Miller', 'Betterton', 12),
('Anatola', 'Fallen', 12),
('Janey', 'Burne', 3),
('Terry', 'Stanney', 11),
('Nero', 'Davisson', 10),
('Delia', 'Arrault', 9),
('Turner', 'Skill', 4),
('Monique', 'Peake', 9),
('Janot', 'Brookshaw', 6),
('Cora', 'Bardwell', 10),
('Harper', 'Willshear', 1),
('Madeleine', 'Mateescu', 8),
('Ailsun', 'Hargraves', 1),
('Brion', 'Sawney', 12),
('Lissie', 'MacCauley', 12),
('Devora', 'Codd', 4),
('Dallas', 'Goadby', 3),
('Xerxes', 'Fowle', 8),
('Stormie', 'Prydie', 7),
('Leia', 'Chesser', 6),
('Grissel', 'Fasham', 9),
('Filippo', 'Nornasell', 11),
('Alexandros', 'Jeffels', 4),
('Adriaens', 'Heinschke', 3),
('Stevana', 'Semmence', 2),
('Maryjane', 'Rosensaft', 2),
('Sterling', 'Dowgill', 8),
('Kittie', 'Tarbatt', 1),
('Engracia', 'Fugere', 7),
('Harli', 'Courtney', 11),
('Vasili', 'Holtom', 12),
('Tiffi', 'Revitt', 7),
('Viki', 'MacGow', 3),
('Francesca', 'Hanburry', 9),
('Marybeth', 'Bisgrove', 9),
('Viviene', 'Bonnick', 11),
('Brandi', 'Bree', 2),
('Kailey', 'Yusupov', 5),
('Timmie', 'Bento', 5),
('Maureene', 'Tellett', 12),
('Moss', 'Suermeiers', 5),
('Karlotte', 'Crunden', 1),
('Karena', 'Whiterod', 12),
('Sherwynd', 'Donativo', 11),
('Margareta', 'Salvadore', 7),
('Chrissie', 'Mathe', 12),
('Griswold', 'Burborough', 1),
('Fredi', 'Ogglebie', 5),
('Thorsten', 'Ashworth', 3),
('Davy', 'Perl', 4),
('Domenic', 'Odell', 9),
('Selma', 'Seyfart', 6),
('Mahmud', 'Smeeth', 7),
('Farlie', 'Prevett', 10),
('Reginald', 'Frichley', 2),
('Ricard', 'Sparshott', 6),
('Rudyard', 'Spraggon', 4),
('Issi', 'Streat', 5),
('Findlay', 'O''Hengerty', 2),
('Lizzy', 'Ricketts', 1),
('Alick', 'Hancke', 10),
('Lucila', 'Scallan', 4),
('Gennifer', 'Wigginton', 4),
('Rory', 'Eliasen', 11),
('Melosa', 'McWilliam', 1),
('Oralia', 'Harefoot', 12),
('Glynda', 'Baggaley', 6),
('Eziechiele', 'Duffit', 5),
('Arman', 'Edgeley', 7),
('Waverley', 'Ace', 9),
('Archibald', 'Spurdon', 7),
('Rivi', 'Imrie', 2),
('Bartolomeo', 'Malone', 1),
('Ab', 'Brand-Hardy', 7),
('Locke', 'Dunican', 10),
('Laurianne', 'Terney', 3),
('Cleve', 'Langfat', 9),
('Lillis', 'Plank', 9),
('Georgeanne', 'Twittey', 5),
('Elyssa', 'Scrooby', 2),
('Valene', 'Capin', 9),
('Malissia', 'Doree', 7),
('Shae', 'Fendlen', 8),
('Danny', 'Oldfield', 7),
('Sonja', 'McJarrow', 5),
('Philip', 'Marc', 9),
('Cesaro', 'Prestney', 6),
('Mendy', 'Clines', 3),
('Lars', 'Stachini', 11);